#!/usr/bin/env bash
# VIGA Environment Setup Script
# Sets up 5 conda environments for 3D reconstruction:
#   viga-agent, viga-blender, viga-sam3d-objects, viga-sam, viga-sam3
#
# Prerequisites:
#   - mamba or conda
#   - git submodules already initialized (git submodule update --init --recursive)
#
# Usage:
#   ./setup.sh                    # all environments
#   ./setup.sh sam3d-objects sam3  # specific environments only
#   ./setup.sh --check            # verify all environments
#   ./setup.sh --check agent sam  # verify specific environments
#
# Available environments: agent, blender, sam3d-objects, sam, sam3

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ──────────────────────────────────────────────
# 1. Utility functions
# ──────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

CONDA_CMD=""
CONDA_ENVS_DIR=""

detect_conda() {
    if command -v mamba &>/dev/null; then
        CONDA_CMD="mamba"
    elif command -v conda &>/dev/null; then
        CONDA_CMD="conda"
    else
        log_error "Neither mamba nor conda found. Please install miniforge or miniconda."
        exit 1
    fi
    # Always use conda for --base (mamba info --base may include extra formatting)
    # Pipe through tr to strip any whitespace/newlines from the output
    CONDA_ENVS_DIR="$(conda info --base 2>/dev/null | tr -d '[:space:]')/envs"
    log_info "Using $CONDA_CMD (envs: $CONDA_ENVS_DIR)"
}

env_exists() {
    local name="$1"
    [ -d "${CONDA_ENVS_DIR}/${name}" ]
}

create_env() {
    local name="$1"
    local python_version="$2"
    if env_exists "$name"; then
        log_warn "Environment '$name' already exists — skipping creation"
    else
        log_info "Creating environment '$name' (Python $python_version)..."
        $CONDA_CMD create -y -n "$name" python="$python_version" --quiet
        log_ok "Created '$name'"
    fi
}

pip_in_env() {
    local env="$1"; shift
    # Run from SCRIPT_DIR so that relative paths in requirements (e.g. -e ./utils/third_party/...)
    # resolve correctly.
    (cd "$SCRIPT_DIR" && "${CONDA_ENVS_DIR}/${env}/bin/pip" "$@")
}

mamba_in_env() {
    local env="$1"; shift
    $CONDA_CMD install -y -n "$env" "$@"
}

detect_gpu_arch() {
    # NOTE: This function returns the arch via stdout. All log messages go to stderr
    # so that callers using $(detect_gpu_arch) get only the arch value.
    if ! command -v nvidia-smi &>/dev/null; then
        log_warn "nvidia-smi not found — defaulting TORCH_CUDA_ARCH_LIST to 8.0" >&2
        echo "8.0"
        return
    fi
    local cc
    cc=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -1 | tr -d '[:space:]')
    if [ -z "$cc" ]; then
        log_warn "Could not detect GPU compute capability — defaulting to 8.0" >&2
        echo "8.0"
    else
        log_info "Detected GPU compute capability: $cc" >&2
        echo "$cc"
    fi
}

# ──────────────────────────────────────────────
# 2. Prerequisite checks
# ──────────────────────────────────────────────

check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v git &>/dev/null; then
        log_error "git not found"
        exit 1
    fi

    if ! command -v wget &>/dev/null; then
        log_error "wget not found (required for model downloads)"
        exit 1
    fi

    if ! command -v nvidia-smi &>/dev/null; then
        log_warn "nvidia-smi not found — GPU-dependent builds may fail"
    fi

    detect_conda
    log_ok "Prerequisites OK"
}

# ──────────────────────────────────────────────
# 3. Config file generation
# ──────────────────────────────────────────────

generate_path_config() {
    local target="${SCRIPT_DIR}/utils/_path.py"
    if [ -f "$target" ]; then
        log_warn "utils/_path.py already exists — skipping (will not overwrite)"
        return
    fi

    log_info "Generating utils/_path.py (CONDA_BASE=${CONDA_ENVS_DIR})..."
    # 1) Write the header + CONDA_BASE with shell expansion (unquoted delimiter)
    cat > "$target" <<EOF
"""Tool script to Python environment path mappings — auto-generated by setup.sh.

All environment names use the 'viga-' prefix to avoid conflicts.
Override CONDA_BASE by setting the VIGA_CONDA_BASE environment variable.
"""
import os
import shutil
from typing import Dict

# Base path for conda environments
CONDA_BASE = os.environ.get(
    "VIGA_CONDA_BASE",
    "${CONDA_ENVS_DIR}"
)
EOF
    # 2) Append the rest with a quoted delimiter (no shell expansion)
    cat >> "$target" << 'PYEOF'

# Environment name to tool script mapping (viga- prefixed)
ENV_MAPPING: Dict[str, str] = {
    # Blender tools (Python 3.11)
    "tools/blender/exec.py": "viga-blender",
    "tools/blender/investigator.py": "viga-blender",
    # Chrome/HTML tools (Python 3.10)
    "tools/exec_html.py": "viga-agent",
    # Core agent tools (Python 3.10)
    "tools/generator_base.py": "viga-agent",
    "tools/initialize_plan.py": "viga-agent",
    "tools/assets/meshy.py": "viga-agent",
    "tools/verifier_base.py": "viga-agent",
    "tools/undo.py": "viga-agent",
    # SAM segmentation tools
    "tools/sam3d/bridge.py": "viga-sam3d-objects",
    "tools/sam3d/init.py": "viga-sam3d-objects",
    "tools/sam3d/sam_worker.py": "viga-sam",
    "tools/sam3d/sam3_worker.py": "viga-sam3",
    "tools/sam3d/sam3d_worker.py": "viga-sam3d-objects",
}


def get_python_path(env_name: str) -> str:
    """Get Python interpreter path for a conda environment."""
    conda_python = os.path.join(CONDA_BASE, env_name, "bin", "python")
    if os.path.exists(conda_python):
        return conda_python
    python_path = shutil.which("python")
    if python_path:
        return python_path
    return "python"


# Build the path_to_cmd mapping
path_to_cmd: Dict[str, str] = {
    tool: get_python_path(env) for tool, env in ENV_MAPPING.items()
}
PYEOF
    log_ok "Generated utils/_path.py"
}

# ──────────────────────────────────────────────
# 4. Per-environment setup functions
# ──────────────────────────────────────────────

setup_agent() {
    local ENV=viga-agent
    log_info "Setting up $ENV..."
    create_env "$ENV" 3.10 || return 1
    pip_in_env "$ENV" install -r "${SCRIPT_DIR}/requirements/requirement_agent.txt" || return 1
    log_ok "$ENV setup complete"
}

setup_blender() {
    local ENV=viga-blender
    log_info "Setting up $ENV..."
    create_env "$ENV" 3.11 || return 1

    # Install requirements (includes -e ./utils/third_party/infinigen)
    pip_in_env "$ENV" install -r "${SCRIPT_DIR}/requirements/requirement_blender.txt" || return 1

    # Install Blender binary via infinigen's script
    local blender_script="${SCRIPT_DIR}/utils/third_party/infinigen/scripts/install/interactive_blender.sh"
    if [ -f "$blender_script" ]; then
        local infinigen_dir="${SCRIPT_DIR}/utils/third_party/infinigen"
        if [ ! -d "${infinigen_dir}/blender" ]; then
            log_info "Installing Blender 4.2 binary..."
            (
                cd "$infinigen_dir"
                INFINIGEN_MINIMAL_INSTALL=True \
                CONDA_PREFIX="${CONDA_ENVS_DIR}/${ENV}" \
                bash scripts/install/interactive_blender.sh
            ) || return 1
            log_ok "Blender binary installed"
        else
            log_info "Blender binary already present — skipping"
        fi
    else
        log_warn "Blender install script not found at $blender_script — skipping binary install"
    fi

    log_ok "$ENV setup complete"
}

setup_sam3d_objects() {
    local ENV=viga-sam3d-objects
    log_info "Setting up $ENV (this will take a while)..."
    create_env "$ENV" 3.11 || return 1

    # 1. PyTorch with CUDA 12.1
    log_info "[$ENV] Installing PyTorch (cu121)..."
    pip_in_env "$ENV" install \
        torch==2.5.1+cu121 torchvision==0.20.1+cu121 torchaudio==2.5.1+cu121 \
        --index-url https://download.pytorch.org/whl/cu121 || return 1

    # 2. CUDA toolkit inside the environment
    log_info "[$ENV] Installing CUDA toolkit 12.1.1..."
    mamba_in_env "$ENV" -c "nvidia/label/cuda-12.1.1" cuda-toolkit || return 1

    # 3. C++ compiler toolchain
    log_info "[$ENV] Installing gxx toolchain..."
    mamba_in_env "$ENV" -c conda-forge gxx_linux-64=11 sysroot_linux-64=2.17 || return 1

    # 4. Set build environment variables
    local ENV_PREFIX="${CONDA_ENVS_DIR}/${ENV}"
    export CUDA_HOME="${ENV_PREFIX}"
    export PATH="${ENV_PREFIX}/bin:${PATH}"
    export LD_LIBRARY_PATH="${ENV_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
    # conda cuda-toolkit puts headers under targets/x86_64-linux/include/ instead of include/
    # CPATH makes them visible to the C++ compiler (nvcc finds them on its own)
    export CPATH="${ENV_PREFIX}/targets/x86_64-linux/include:${CPATH:-}"

    local ARCH_LIST
    ARCH_LIST="$(detect_gpu_arch)"
    export TORCH_CUDA_ARCH_LIST="$ARCH_LIST"

    log_info "[$ENV] Building with CUDA_HOME=$CUDA_HOME TORCH_CUDA_ARCH_LIST=$ARCH_LIST"

    # 5. Compile native extensions
    log_info "[$ENV] Building diff-gaussian-rasterization..."
    pip_in_env "$ENV" install --no-build-isolation \
        "git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git@59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d" || return 1

    log_info "[$ENV] Building nvdiffrast..."
    pip_in_env "$ENV" install --no-build-isolation \
        "git+https://github.com/NVlabs/nvdiffrast.git@253ac4fcea7de5f396371124af597e6cc957bfae" || return 1

    log_info "[$ENV] Building gsplat..."
    pip_in_env "$ENV" install --no-build-isolation \
        "git+https://github.com/nerfstudio-project/gsplat.git@2323de5905d5e90e035f792fe65bad0fedd413e7" || return 1

    log_info "[$ENV] Building pytorch3d..."
    pip_in_env "$ENV" install --no-build-isolation \
        "git+https://github.com/facebookresearch/pytorch3d.git@75ebeeaea0908c5527e7b1e305fbc7681382db47" || return 1

    log_info "[$ENV] Installing psutil..."
    pip_in_env "$ENV" install psutil==7.1.3 || return 1

    log_info "[$ENV] Building flash-attn..."
    pip_in_env "$ENV" install flash-attn==2.8.3 --no-build-isolation || return 1

    log_info "[$ENV] Installing kaolin..."
    pip_in_env "$ENV" install kaolin==0.17.0 \
        -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu121.html || return 1

    # 6. Main requirements (--no-deps since dependencies were installed above)
    log_info "[$ENV] Installing remaining requirements..."
    pip_in_env "$ENV" install -r "${SCRIPT_DIR}/requirements/requirement_sam3d-objects.txt" --no-deps || return 1

    # 7. HuggingFace model download
    log_info "[$ENV] Installing huggingface-hub CLI..."
    pip_in_env "$ENV" install 'huggingface-hub[cli]==0.36.0' || return 1

    local sam3d_dir="${SCRIPT_DIR}/utils/third_party/sam3d"
    local ckpt_dir="${sam3d_dir}/checkpoints/hf"
    if [ -d "$ckpt_dir" ] && [ "$(ls -A "$ckpt_dir" 2>/dev/null)" ]; then
        log_info "[$ENV] SAM3D checkpoints already present — skipping download"
    else
        log_info "[$ENV] Downloading SAM3D model (facebook/sam-3d-objects)..."
        (
            cd "$sam3d_dir"
            "${CONDA_ENVS_DIR}/${ENV}/bin/huggingface-cli" download \
                --repo-type model \
                --local-dir checkpoints/hf-download \
                --max-workers 1 \
                facebook/sam-3d-objects
            mv checkpoints/hf-download/checkpoints checkpoints/hf
            rm -rf checkpoints/hf-download
        ) || return 1
        log_ok "[$ENV] SAM3D model downloaded"
    fi

    log_ok "$ENV setup complete"
}

setup_sam() {
    local ENV=viga-sam
    log_info "Setting up $ENV..."
    create_env "$ENV" 3.10 || return 1
    pip_in_env "$ENV" install -r "${SCRIPT_DIR}/requirements/requirement_sam.txt" || return 1

    # Download SAM ViT-H checkpoint
    local sam_ckpt="${SCRIPT_DIR}/utils/third_party/sam/sam_vit_h_4b8939.pth"
    if [ -f "$sam_ckpt" ]; then
        log_info "SAM checkpoint already present — skipping download"
    else
        log_info "Downloading SAM ViT-H checkpoint..."
        wget -q -P "${SCRIPT_DIR}/utils/third_party/sam" \
            https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth || return 1
        log_ok "SAM checkpoint downloaded"
    fi

    log_ok "$ENV setup complete"
}

setup_sam3() {
    local ENV=viga-sam3
    log_info "Setting up $ENV..."
    create_env "$ENV" 3.11 || return 1
    pip_in_env "$ENV" install -r "${SCRIPT_DIR}/requirements/requirement_sam3.txt" \
        --extra-index-url https://download.pytorch.org/whl/cu126 || return 1
    log_ok "$ENV setup complete"
}

# ──────────────────────────────────────────────
# 5. Environment check (--check)
# ──────────────────────────────────────────────

# Run a Python import check in a given environment. Returns 0 on success.
try_import() {
    local env="$1"; shift
    "${CONDA_ENVS_DIR}/${env}/bin/python" -c "$*" 2>/dev/null
}

check_agent() {
    try_import viga-agent "import openai, anthropic, mcp; print('OK')"
}

check_blender() {
    try_import viga-blender "import infinigen; print('OK')"
}

check_sam3d_objects() {
    try_import viga-sam3d-objects "
import torch
assert torch.cuda.is_available(), 'CUDA not available'
import diff_gaussian_rasterization, nvdiffrast, gsplat, pytorch3d
print(f'OK (torch {torch.__version__}, CUDA {torch.version.cuda})')
"
}

check_sam() {
    try_import viga-sam "import segment_anything; print('OK')"
    local sam_ckpt="${SCRIPT_DIR}/utils/third_party/sam/sam_vit_h_4b8939.pth"
    if [ ! -f "$sam_ckpt" ]; then
        log_warn "SAM checkpoint not found: $sam_ckpt"
        return 1
    fi
}

check_sam3() {
    try_import viga-sam3 "import sam3; print('OK')"
}

run_checks() {
    local targets=("$@")

    echo ""
    echo "╔══════════════════════════════════════╗"
    echo "║       VIGA Environment Check         ║"
    echo "╚══════════════════════════════════════╝"
    echo ""

    declare -A CHECK_FN=(
        [agent]=check_agent
        [blender]=check_blender
        [sam3d-objects]=check_sam3d_objects
        [sam]=check_sam
        [sam3]=check_sam3
    )

    local passed=0
    local total=${#targets[@]}

    for env in "${targets[@]}"; do
        local env_name="viga-${env}"
        if ! env_exists "$env_name"; then
            log_error "$env_name — not found"
            continue
        fi

        local result
        result=$( "${CHECK_FN[$env]}" 2>&1 ) && {
            log_ok "$env_name — $result"
            passed=$((passed + 1))
        } || {
            log_error "$env_name — FAIL"
            if [ -n "$result" ]; then
                echo "       $result"
            fi
        }
    done

    echo ""
    if [ "$passed" -eq "$total" ]; then
        log_ok "All $total environments OK"
    else
        log_error "$passed/$total environments passed"
        return 1
    fi
}

# ──────────────────────────────────────────────
# 6. Main
# ──────────────────────────────────────────────

ALL_ENVIRONMENTS=(agent blender sam3d-objects sam sam3)

main() {
    echo ""
    echo "╔══════════════════════════════════════╗"
    echo "║         VIGA Environment Setup       ║"
    echo "╚══════════════════════════════════════╝"
    echo ""

    check_prerequisites

    # Use arguments if provided, otherwise all environments
    local targets=()
    if [ $# -gt 0 ]; then
        for arg in "$@"; do
            if [[ ! " ${ALL_ENVIRONMENTS[*]} " =~ " ${arg} " ]]; then
                log_error "Unknown environment: $arg"
                log_info "Available: ${ALL_ENVIRONMENTS[*]}"
                return 1
            fi
            targets+=("$arg")
        done
    else
        targets=("${ALL_ENVIRONMENTS[@]}")
    fi

    log_info "Environments: ${targets[*]}"
    echo ""

    # Config file generation
    generate_path_config
    echo ""

    # Environment setup
    local succeeded=()
    local failed=()

    declare -A SETUP_FN=(
        [agent]=setup_agent
        [blender]=setup_blender
        [sam3d-objects]=setup_sam3d_objects
        [sam]=setup_sam
        [sam3]=setup_sam3
    )

    for env in "${targets[@]}"; do
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        # Run in subshell; each function uses || return 1 for error propagation
        if ( "${SETUP_FN[$env]}" ); then
            succeeded+=("$env")
        else
            log_error "Failed to set up $env"
            failed+=("$env")
        fi
    done

    # Summary
    echo ""
    echo "╔══════════════════════════════════════╗"
    echo "║             Setup Summary            ║"
    echo "╚══════════════════════════════════════╝"
    echo ""

    if [ ${#succeeded[@]} -gt 0 ]; then
        log_ok "Succeeded (${#succeeded[@]}):"
        for env in "${succeeded[@]}"; do
            echo "       viga-${env}"
        done
    fi

    if [ ${#failed[@]} -gt 0 ]; then
        echo ""
        log_error "Failed (${#failed[@]}):"
        for env in "${failed[@]}"; do
            echo "       viga-${env}"
        done
    fi

    echo ""
    echo "Next steps:"
    echo "  1. Set API keys as environment variables:"
    echo "       export OPENAI_API_KEY=sk-..."
    echo "       export CLAUDE_API_KEY=sk-ant-..."
    echo "  2. Verify an environment:"
    echo "       ${CONDA_ENVS_DIR}/viga-agent/bin/python -c \"import openai; print('OK')\""
    echo "  3. Run VIGA:"
    echo "       python main.py --mode blendergym --model gpt-4o"
    echo ""

    if [ ${#failed[@]} -gt 0 ]; then
        return 1
    fi
}

# Entry point: dispatch --check or run main setup
if [ "${1:-}" = "--check" ]; then
    shift
    detect_conda
    targets=()
    if [ $# -gt 0 ]; then
        for arg in "$@"; do
            if [[ ! " ${ALL_ENVIRONMENTS[*]} " =~ " ${arg} " ]]; then
                log_error "Unknown environment: $arg"
                log_info "Available: ${ALL_ENVIRONMENTS[*]}"
                exit 1
            fi
            targets+=("$arg")
        done
    else
        targets=("${ALL_ENVIRONMENTS[@]}")
    fi
    run_checks "${targets[@]}"
else
    main "$@"
fi
